---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-disk-sas
