apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-metadata
rules: []
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: git-metadata
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: git-metadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-metadata
subjects:
  - kind: ServiceAccount
    name: git-metadata
