name = "community-metadata"
timezone = "PRC"
httpPort = 9500

[log]
logFile = "/app/logs/run-application-{date}.log"
errFile = "/app/logs/run-error-{date}.log"

[manager]
syncInterval = 30
notifyInterval = 30
baseFolder = "/app/repos/"
gitSyncPath = "/app/git-sync"

[plugins.helloworld]
enabled = false
[plugins.openeulermirrors]
enabled = false
[plugins.openeulersigs]
enabled = false
[plugins.playgroundmeta]
enabled = true
[plugins.openeulermoocstudio]
enabled = true
[plugins.opengaussmoocstudio]
enabled = true