name = "community-metadata"
debug = false
timezone = "PRC"
httpPort = 9500

[log]
logFile = "/data/logs/run-application-{date}.log"
errFile = "/data/logs/run-error-{date}.log"

[cache]
disable = true
db = 1
auth = "123456"
server = "127.0.0.1:6379"
prefix = "cache"

[manager]
syncInterval = 30
notifyInterval = 30
baseFolder = "/data/repos/"
gitSyncPath = "/app/git-sync"
