name = "community-metadata"
timezone = "PRC"
httpPort = 9500

[log]
logFile = "/app/logs/run-application-{date}.log"
errFile = "/app/logs/run-error-{date}.log"

[manager]
syncInterval = 30
notifyInterval = 30
baseFolder = "/app/repos/"
gitSyncPath = "/app/git-sync"

[plugins]
    [plugins.helloworld]
    enabled = false
    [plugin.openeulermirrors]
    enabled = true
    [plugin.openeulersigs]
    enabled = true
