httpPort = 9500
[log]
logFile = "./logs/info-{date}.log"
errFile = "./logs/error-{date}.log"
[manager]
syncInterval = 30
notifyInterval = 30
baseFolder = "./repos"
gitSyncPath = "/usr/loca/bin/git-sync"

[plugins.helloworld]
enabled = false
[plugins.openeulermirrors]
enabled = false
[plugins.openeulersigs]
enabled = false
[plugins.playgroundmeta]
enabled = true