on: [push, pull_request]

jobs:
  validate-dockerfile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@master
        with:
          # https://github.com/fluxcd/flux/blob/master/docker/kubectl.version
          kubectl: 1.14.7
          # https://github.com/fluxcd/flux/blob/master/docker/kustomize.version
          kustomize: 3.2.3
          # https://github.com/fluxcd/helm-operator/blob/master/docker/helm.version
          # helm: 2.14.3
          command: |
            #!/bin/bash
            kustomize build  "./deploy" | kubeval --strict --ignore-missing-schemas
